export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  SIGNUP: "/signup",
  FORGOT_PASSWORD: "/forgot-password",
  DASHBOARD: "/dashboard",
  PROJECT: "/projects/:projectId",
  PROJECT_RULES: "/projects/:projectId/rules",
  PROJECT_TEMPLATES: "/projects/:projectId/templates",
  PROJECT_TEMPLATE_NEW: "/projects/:projectId/templates/new",
  PROJECT_TEMPLATE_EDIT: "/projects/:projectId/templates/:templateId",
  PROJECT_CARDS: "/projects/:projectId/cards",
  PROJECT_CARD_NEW: "/projects/:projectId/cards/new",
  PROJECT_CARD_DETAIL: "/projects/:projectId/cards/:cardId",
  PROJECT_CARD_EDIT: "/projects/:projectId/cards/:cardId/edit",
  PROJECT_AI_CREATE: "/projects/:projectId/ai-create",
  CARDS: "/cards",
  EXPORT: "/export",
  SETTINGS: "/settings",
} as const;
